name: "Issue-based Release PR"
description: "Create a release Pull-Request that lists completed issues"
inputs:
  base-branch-name:
    default: "develop"
    description: ""
    required: true  # TODO: default があるのに required ？
  # conditions-for-uncompleted-issues:
  # release-branch-name-pattern:
  #   default: 'release/v{version}'
  # release-pr-name-pattern:
  # start-date:
  # target-branch-name:
  #   default: 'main'
runs:
  using: "node16"
  main: "./cli.js"
