name: "Issue-based Release PR"
description: "Create a release Pull-Request that lists completed issues"
inputs:
  base-branch-name:
    default: "develop"
    description: ""
    required: true  # TODO: default があるのに required ？
  github-token:
    # TODO: 必要な権限をちゃんと書く。多分 Issue = RO, PR = RO, (最初から付いてて外せない) Metadata = RO のみ。
    description: ""
    required: true
  # conditions-for-uncompleted-issues:
  # release-branch-name-pattern:
  #   default: 'release/v{version}'
  # release-pr-name-pattern:
  # start-date:
  # target-branch-name:
  #   default: 'main'
runs:
  using: "node16"
  main: "./dist/index.js"
