on: [push]

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: issue-based-release-pr
        name: Run issue-based-release-pr
        uses: ./
        with:
          base-branch-name: 'Hello branch name!'
